#!/usr/bin/php
<?php
require __DIR__ . '/app/init.php';

use PonHelper\App;
use Symfony\Component\Console\Application;

$container = App::getInstance()->getContainer();
$config = App::getInstance()->conf('console');

$app = new Application();
$app->setName($config['name']);
$app->setVersion($config['version']);
foreach ($config['handlers'] as $handler) {
    $app->add($container->get($handler));
}
$app->run();

