<?php


namespace PonHelper\Console;


use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class RunServerCommand extends AbstractCommand
{
    function configure()
    {
        $this->setName('server:run')
            ->setDescription("Start local web server")
            ->addOption("interface", 'i',InputOption::VALUE_OPTIONAL, "Listen interface", 'localhost')
            ->addOption("port", "p", InputOption::VALUE_OPTIONAL, "Listen port", 8000);
        parent::configure(); // TODO: Change the autogenerated stub
    }
    function execute(InputInterface $input, OutputInterface $output)
    {
        $output->setVerbosity(OutputInterface::VERBOSITY_DEBUG);
        $workDir = __DIR__ . '/../../public';
        system ("cd $workDir && php -S {$input->getOption('interface')}:{$input->getOption('port')}");
    }
}