<?php


namespace PonHelper\Module;


use PonHelper\Console\AbstractCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

abstract class AbstractConsole extends AbstractCommand
{
    final function run(InputInterface $input, OutputInterface $output)
    {
        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }
    abstract function config();
    abstract function start(InputInterface $input, OutputInterface $output);
    final function execute(InputInterface $input, OutputInterface $output)
    {
        $this->start($input,$output);
        return self::SUCCESS;
    }
}